basePath: /api/v1
definitions:
  database.AddUser:
    properties:
      password:
        format: password
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  database.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  database.Message:
    properties:
      message:
        type: string
    type: object
  database.Token:
    properties:
      token:
        type: string
    type: object
  database.User:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  database.UserInformation:
    properties:
      id:
        type: string
      username:
        type: string
    type: object
host: localhost:9003
info:
  contact: {}
  description: List APIs of UserManagement Service
  termsOfService: http://swagger.io/terms/
  title: UserManagement Service API Document
  version: "1.0"
paths:
  /admin/auth:
    post:
      consumes:
      - multipart/form-data
      description: Authenticate user
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        format: password
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.Token'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/database.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/database.Error'
      security:
      - ApiKeyAuth: []
      summary: Check user authentication
      tags:
      - admin
  /users:
    get:
      consumes:
      - application/json
      description: Get a users by username parameter
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Username
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.UserInformation'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/database.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/database.Error'
      summary: Get a users by username parameter
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Add a new user
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Add user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/database.AddUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/database.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/database.Error'
      summary: Add a new user
      tags:
      - user
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a user by ID
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/database.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/database.Error'
      summary: Delete a user by ID
      tags:
      - user
    patch:
      consumes:
      - application/json
      description: Update an existing user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/database.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.UserInformation'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/database.Error'
      summary: Update an existing user
      tags:
      - user
  /users/detail/{id}:
    get:
      consumes:
      - application/json
      description: Get a user by ID
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.UserInformation'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/database.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/database.Error'
      summary: Get a user by ID
      tags:
      - user
  /users/list:
    get:
      consumes:
      - application/json
      description: List all existing users
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.UserInformation'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/database.Error'
      summary: List all existing users
      tags:
      - user
swagger: "2.0"
